<a href="https://colab.research.google.com/github/caro0020/datamining/blob/main/Ejercicio3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Revision Inicial

In [2]:
import pandas as pd
import numpy as np

In [3]:
url = "https://raw.githubusercontent.com/caro0020/datamining/refs/heads/main/archivos/Ejercicio%203.csv"
df = pd.read_csv(url)
df.head()

   Weight  Cholesterol  Gender
0     102          111       1
1     115          135       1
2     115          136       1
3     140          167       0
4     130          158       1

In [4]:
df.shape

(547, 3)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Weight       547 non-null    int64
 1   Cholesterol  547 non-null    int64
 2   Gender       547 non-null    int64
dtypes: int64(3)
memory usage: 12.9 KB

In [6]:
df.isnull().sum()

Weight         0
Cholesterol    0
Gender         0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(57)

In [8]:
df.describe()

           Weight  Cholesterol      Gender
count  547.000000   547.000000  547.000000
mean   143.572212   170.433272    0.513711
std     30.837275    39.147189    0.500269
min     95.000000   102.000000    0.000000
25%    116.000000   136.000000    0.000000
50%    140.000000   169.000000    1.000000
75%    171.000000   208.000000    1.000000
max    203.000000   235.000000    1.000000

In [9]:
df["Gender"].value_counts()

Gender
1    281
0    266
Name: count, dtype: int64

In [10]:
variables_numericas = ["Weight", "Cholesterol"]

for columna in variables_numericas:
    media = df[columna].mean()
    desviacion = df[columna].std()

    limite_inferior = media - 2 * desviacion
    limite_superior = media + 2 * desviacion

    atipicos = df[
        (df[columna] < limite_inferior) |
        (df[columna] > limite_superior)
    ]

    print("Variable:", columna)
    print("Media:", round(media, 2))
    print("Desviación estándar:", round(desviacion, 2))
    print("Límite inferior:", round(limite_inferior, 2))
    print("Límite superior:", round(limite_superior, 2))
    print("Cantidad de valores atípicos:", len(atipicos))

Variable: Weight
Media: 143.57
Desviación estándar: 30.84
Límite inferior: 81.9
Límite superior: 205.25
Cantidad de valores atípicos: 0
Variable: Cholesterol
Media: 170.43
Desviación estándar: 39.15
Límite inferior: 92.14
Límite superior: 248.73
Cantidad de valores atípicos: 0